name: parkliapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0        # قللنا النسخة عشان تتوافق مع نظامك
  latlong2: ^0.9.0
  geolocator: ^11.0.0       # نسخة مستقرة للأنظمة القديمة
  url_launcher: ^6.2.0
  supabase_flutter: ^2.4.0  # نسخة تتوافق مع Dart 3.4.0
  app_links: ^6.0.0
  image_picker: ^1.0.7      # النسخة اللي طلبها الماك قبل شوي
  firebase_core: ^2.30.0    # نسخ متوافقة مع إصدار الماك والـ SDK
  firebase_auth: ^4.19.0
  http: ^1.2.0
  shared_preferences: ^2.2.0 # النسخة اللي رضي فيها جهازك


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/